/**
 * Cross-language identity: the deterministic generators (greedy + repair) must
 * produce byte-identical edge sets to the Python reference. The fixtures in
 * reference.json were generated by gen_c_cached.ring_greedy_cached. Any drift
 * here means the ports diverged.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ringGreedy } from "../src/core/greedy.js";
import { allPairsSummary, girth } from "../src/core/metrics.js";
import { mooreLowerBounds, cycleAspl } from "../src/core/bounds.js";

const here = dirname(fileURLToPath(import.meta.url));
const ref = JSON.parse(
  readFileSync(join(here, "fixtures", "reference.json"), "utf8"),
);

describe("greedy byte-identity vs Python", () => {
  for (const fx of ref.greedy) {
    it(`n=${fx.n} k=${fx.k} repair=${fx.repair}`, () => {
      const { graph, finalMind } = ringGreedy(fx.n, fx.k, {
        mind: fx.mind,
        repair: fx.repair,
      });
      const edges = graph.edgeList();
      // identical edge count
      expect(edges.length).toBe(fx.num_edges);
      // identical edge set (both sorted ascending)
      expect(edges).toEqual(fx.edges.map((e: number[]) => [e[0], e[1]]));
      // identical demoted mind
      expect(finalMind).toBe(fx.final_mind);
      // identical degree sequence
      expect(graph.degrees()).toEqual(fx.degrees);
      // identical derived metrics
      const { aspl, diameter } = allPairsSummary(graph);
      expect(aspl).toBeCloseTo(fx.aspl, 9);
      expect(diameter).toBe(fx.diameter);
      expect(girth(graph)).toBe(fx.girth);
    });
  }
});

describe("Moore bounds match Python", () => {
  for (const m of ref.moore) {
    it(`n=${m.n} k=${m.k}`, () => {
      const { asplLb, diameterLb } = mooreLowerBounds(m.n, m.k);
      expect(asplLb).toBeCloseTo(m.aspl_lb, 9);
      expect(diameterLb).toBe(m.diam_lb);
    });
  }
});

describe("cycle ASPL matches Python", () => {
  for (const [nStr, val] of Object.entries(ref.metrics.cycle_aspl)) {
    it(`C_${nStr}`, () => {
      expect(cycleAspl(Number(nStr))).toBeCloseTo(val as number, 9);
    });
  }
});
